MvcCoreUtilidades/Controllers/CachingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace MvcCoreUtilidades.Controllers
{
    public class CachingController : Controller
    {
        private IMemoryCache memoryChache;

        public CachingController(IMemoryCache memoryChache)
        {
            this.memoryChache = memoryChache;
        }
        //PODEMOS INDICAR EL TIEMPO EN SEGUNDOS PARA QUE RESPONDA DE NUEVO AL ACTION
        [ResponseCache(Duration = 15, Location =ResponseCacheLocation.Client)]
        public IActionResult MemoriaDistribuida()
        {
            string fecha = DateTime.Now.ToLongDateString() + "--" + DateTime.Now.ToLongTimeString();
            ViewData["FECHA"] = fecha;
            return View();
        }
        public IActionResult MemoriaPersonalizada(int? tiempo)
        {   
            //LA PIRMERA VEZ NO RECIBIMOS TEIMPO
            //VAMOS A PONER UN TIEMPO DE 60 SEGUNDOS
            if(tiempo == null)
            {
                tiempo = 5;
            }
            string fecha = DateTime.Now.ToLongDateString() + "--" + DateTime.Now.ToLongTimeString();
            //PREGUNTAMOS SI EXISTE ALGO EN CACHE O NO EXISTE
            if(this.memoryChache.Get("FECHA") == null)
            {
                //NO EXISTE NADA EN CACHE TODAVIA
                //CREAMOS LAS OPCIONES PARA EL CACHE CON TIEMPO
                MemoryCacheEntryOptions options = new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromSeconds(tiempo.Value));
                this.memoryChache.Set("FECHA", fecha, options);
                ViewData["MENSAJE"] = "Almacenando en cache";
                ViewData["FECHA"] = this.memoryChache.Get("FECHA");
            }
            else
            {
                //TENEMOS LA FECHA EN CACHE
                fecha = this.memoryChache.Get<string>("FECHA");
                ViewData["MENSAJE"] = "Recuperando de cache";
                ViewData["FECHA"] = fecha;
            }
            return View();
        }
    }
}

MvcCoreUtilidades/Controllers/CifradosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Helpers;

namespace MvcCoreUtilidades.Controllers
{
    public class CifradosController : Controller
    {
        public IActionResult CifradoBasico()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CifradoBasico(string contenido, string resultado, string accion)
        {
            //CIFRAMOS EL CONTENIDO RECIBIDO
            string response = HelperCryptography.EncriptarTextoBasico(contenido);
            if (accion.ToLower() == "cifrar")
            {
                ViewData["TEXTOCIFRADO"] = response;
            } else if (accion.ToLower() == "comparar")
            {
                //COMPARAMOS LA RESPUESTA CIFRADA CON EL VALOR DE LA CAJA RESULTADO
                if(response != resultado)
                {
                    ViewData["MENSAJE"] = "Los valores no coinciden";
                }
                else
                {
                    ViewData["MENSAJE"] = "Los valores son iguales";
                }
            }

            return View();
        }
        public IActionResult CifradoEficiente()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CifradoEficiente(string contenido, string resultado, string accion)
        {   
            if (accion.ToLower() == "cifrar")
            {
                //CIFRAMOS GENERANOD UN NUEVO SALT
                string response = HelperCryptography.EncriptarContenido(contenido, false);
                ViewData["TEXTOCIFRADO"] = response;
            }else if (accion.ToLower() == "comparar")
            {
                string response = HelperCryptography.EncriptarContenido(contenido, true);
                if (response != resultado)
                {
                    ViewData["MENSAJE"] = "<h1 style='color:red'> Los datos NO coinciden </h1>";
                }
                else
                {
                    ViewData["MENSAJE"] = "<h1 style='color:green'> Los datos SI coinciden </h1>";
                }
            }
            return View();
        }
    }
}

MvcCoreUtilidades/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Models;

namespace MvcCoreUtilidades.Controllers
{
    public class CochesController : Controller
    {
        private List<Coche> Cars;

        public CochesController()
        {
            this.Cars = new List<Coche>

              {

                  new Coche { IdCoche = 1, Marca = "Pontiac"

                  , Modelo = "Firebird", Imagen = "https://mudfeed.com/wp-content/uploads/2021/08/KITT-1200x640.jpg"},

                  new Coche { IdCoche = 2, Marca = "Volkswagen"

                  , Modelo = "Escarabajo", Imagen = "https://www.quadis.es/documents/80345/95274/herbie-el-volkswagen-beetle-mas.jpg"},

                  new Coche { IdCoche = 3, Marca = "Ferrari"

                  , Modelo = "Testarrosa", Imagen = "https://www.lavanguardia.com/files/article_main_microformat/uploads/2017/01/03/5f15f8b7c1229.png"},

                  new Coche { IdCoche = 4, Marca = "Ford"

                  , Modelo = "Mustang GT", Imagen = "https://cdn.autobild.es/sites/navi.axelspringer.es/public/styles/1200/public/media/image/2018/03/prueba-wolf-racing-mustang-gt.jpg"}

              };
        }
        //AQUI SOLAMENTE MOSTRAMOS LA LISTA INDEX
        public IActionResult Index()
        {

            return View();
        }
        //NECESITAMOS UNA PETICION IACTIONRESULT QUE CARGARA LOS COCHES, DICHA PETICION IRA INTEGRADA DENTRO DE OTRA VISTA(INDEX)
        public IActionResult _CochesPartial()
        {
            //SI VAMOS A UTILZAR UNA VISTA PARCIAL CON AJAX DEBEMOS DEVOLVER PartialView()
            //Y EL MODEL SI LO NECESITAMOS
            return PartialView("_CochesPartial", this.Cars);
        }
        public IActionResult _DetailsCoche(int idcoche)
        {
            Coche car = this.Cars.FirstOrDefault(x => x.IdCoche == idcoche);
            return PartialView("_DetailsCoche", car);
        }
    }
}

MvcCoreUtilidades/Controllers/MailExampleController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Helpers;
using System.Net;
using System.Net.Mail;

namespace MvcCoreUtilidades.Controllers
{
    public class MailExampleController : Controller
    {   
        //NECESITAMOS RECUPERAR LAS CLAVES DE SETTINGS
        private HelperUploadFiles helperUploadFiles;
        private HelperMails helperMails;

        public MailExampleController(HelperMails helperMails, HelperUploadFiles helperUploadFiles)
        {
            this.helperUploadFiles = helperUploadFiles;
            this.helperMails = helperMails;
        }

        public IActionResult SendMail()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SendMail(string para, string asunto, string mensaje, IFormFile file)
        {
            if (file != null)
            {
                string path = await helperUploadFiles.UploadFileAsync(file, Folders.Mails);
                await this.helperMails.SendMailsAsync(para, asunto, mensaje, path);
            }
            else
            {
                await helperMails.SendMailsAsync(para, asunto, mensaje);
            }      
            ViewData["MENSAJE"] = "Email enviado correctamente";
            return View();
        }
    }
}

MvcCoreUtilidades/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreUtilidades</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreUtilidades.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreUtilidades</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UploadFiles" asp-action="SubirFichero">Upload Files</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MailExample" asp-action="SendMail">Send Mails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cifrados" asp-action="CifradoBasico">Cifrado Basico</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cifrados" asp-action="CifradoEficiente">Cifrado Eficiente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caching" asp-action="MemoriaPersonalizada">Memoria Personalizada</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caching" asp-action="MemoriaDistribuida">Memoria Distribuida</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coches" asp-action="Index">Coches AJAX</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <partial name="_MenuUsuario" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcCoreUtilidades - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcCoreUtilidades/Views/Shared/_MenuUsuario.cshtml
@{
    string usuario = Context.Session.GetString("USUARIO");
}

@if ( usuario == null)
{
    <li class="nav-item"> 
        <a asp-controller="Home" asp-action="Login" class="nav-link">
            Log In
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a asp-controller="Home" asp-action="Logout" class="nav-link">
            Cerrar sesión @usuario
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Home" asp-action="Perfil" class="nav-link">
            Perfil
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Home" asp-action="Pedidos" class="nav-link">
            Pedidos
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Home" asp-action="Comentarios" class="nav-link">
            Comentarios
        </a>
    </li>
}